# ARK API chart values

# Global annotations added to all resources
global:
  annotations:
    ark.mckinsey.com/service: ark-api

# Application configuration
app:
  name: ark-api
  image:
    repository: ghcr.io/mckinsey/agents-at-scale-ark/ark-api
    # tag defaults to .Chart.AppVersion if not specified
    pullPolicy: IfNotPresent
  
  # Resource configuration
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  # Environment variables - often useful to allow other websites to hit the
  # APIs - not suitable for production environments.
  env:
    - name: CORS_ORIGINS
      value: "*"
    # Authentication environment variables
    - name: OIDC_ISSUER_URL
      value: ""
    - name: OIDC_APPLICATION_ID
      value: ""
    - name: AUTH_MODE
      value: "open"
  # Optional: Import entire secrets/configmaps as env vars
  # envFrom:
  #   - secretRef:
  #       name: azure-openai-secret
  #       optional: true

# Service configuration
service:
  name: ark-api
  type: ClusterIP
  port: 80
  targetPort: 8000

# Ingress configuration (legacy routing method)
# Disabled by default. Use this for traditional Kubernetes Ingress routing.
# For newer deployments, consider using HTTPRoute (below) with Gateway API instead.
ingress:
  enabled: false
  className: ""  # e.g., "nginx", "traefik", "kong"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: ark-api.example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: ark-api-tls
  #    hosts:
  #      - ark-api.example.local

# HTTPRoute configuration (Gateway API - modern routing method)
# Disabled by default. This is the preferred routing method for Kubernetes 1.23+
# with Gateway API CRDs installed. Example values below show localhost development setup.
httpRoute:
  enabled: false
  annotations: {}
    # Custom annotations can be added here
  # Gateway references
  parentRefs:
    - name: localhost-gateway
      namespace: ark-system
  # Hostnames this route matches
  hostnames:
    - "ark-api.127.0.0.1.nip.io"
    - "ark-api.default.127.0.0.1.nip.io"

# Service account configuration
serviceAccount:
  name: ark-api-sa
  create: true
