# DevSpace configuration for {{ .Values.project.name }}
version: v2beta1

# Deployment pipelines
pipelines:
  deploy: |-
    build_images --all
    create_deployments --all

  dev: |-
    create_deployments --all
    start_dev --all

# Image build configuration
images:
  {{ .Values.project.name }}:
    image: {{ .Values.devspace.image.repository }}
    dockerfile: ./Dockerfile
    context: ./

# Kubernetes deployments
deployments:
  {{ .Values.project.name }}:
    namespace: {{ .Values.devspace.namespace }}
    helm:
      chart:
        path: ./chart
      values:
        app:
          image:
            repository: ${runtime.images.{{ .Values.project.name }}.image}
            tag: ${runtime.images.{{ .Values.project.name }}.tag}

# Development configuration
dev:
  {{ .Values.project.name }}:
    imageSelector: {{ .Values.project.name }}
    devImage: python:{{ .Values.python.version }}-slim
    command: ["sh", "-c", "cd /app && python -m {{ .Values.python.module_name }}"]
    namespace: {{ .Values.devspace.namespace }}
    logs:
      lastLines: 50
    sync:
      - path: ./:/app
        uploadExcludeFile: .dockerignore
        startContainer: true
    ssh:
      enabled: true