# ARK MCP chart values

# Global annotations added to all resources
global:
  annotations:
    ark.mckinsey.com/service: ark-mcp

# Application configuration
app:
  name: ark-mcp
  image:
    repository: ghcr.io/mckinsey/agents-at-scale-ark/ark-mcp
    # tag defaults to .Chart.AppVersion if not specified
    pullPolicy: IfNotPresent
  
  # Resource configuration
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  

# Service configuration
service:
  name: ark-mcp
  type: ClusterIP
  port: 80
  targetPort: 2627

# Ingress configuration (legacy routing method)
# Disabled by default. Use this for traditional Kubernetes Ingress routing.
# For newer deployments, consider using HTTPRoute (below) with Gateway API instead.
ingress:
  enabled: false
  className: ""  # e.g., "nginx", "traefik", "kong"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: ark-mcp.example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: ark-mcp-tls
  #    hosts:
  #      - ark-mcp.example.local

# HTTPRoute configuration (Gateway API - modern routing method)
# Disabled by default. This is the preferred routing method for Kubernetes 1.23+
# with Gateway API CRDs installed. Example values below show localhost development setup.
httpRoute:
  enabled: false
  annotations: {}
    # Custom annotations can be added here
  # Gateway references
  parentRefs:
    - name: localhost-gateway
      namespace: ark-system
  # Hostnames this route matches
  hostnames:
    - "ark-mcp.default.127.0.0.1.nip.io"

# Service account configuration
serviceAccount:
  name: ark-mcp-sa
  create: true
