{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ark-tenant.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ark-tenant.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "ark-tenant.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.rbac.additionalSubjects }}
{{- toYaml . | nindent 0 }}
{{- end }}
roleRef:
  kind: Role
  name: {{ include "ark-tenant.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}