#!/usr/bin/env python3
"""
Get Weather Tool for ARK
Generated by ark dev tool init
"""

from fastmcp import FastMCP

# Initialize the MCP server
mcp = FastMCP("get_weather")

@mcp.tool()
def get_weather(query: str) -> str:
    """
    Get Weather
    
    Args:
        query: The input query or parameters for the tool
        
    Returns:
        The result of the get_weather operation
    """
    # TODO: Implement your tool logic here
    return f"Get Weather result for query: {query}"

# Additional tools can be added here
# @mcp.tool()
# def another_tool(param: str) -> str:
#     """Another tool description"""
#     return f"Result: {param}"

if __name__ == "__main__":
    # Run the MCP server
    mcp.run()
