# Helm chart values for Python MCP tool deployment
app:
  name: python-mcp-tool
  image:
    repository: python-mcp-tool
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080

  resources:
    limits:
      memory: "256Mi"
      cpu: "200m"
    requests:
      memory: "128Mi"
      cpu: "100m"