apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ark-cluster-memory.fullname" . }}
  labels:
    {{- include "ark-cluster-memory.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ark-cluster-memory.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ark-cluster-memory.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ark-cluster-memory.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.memory.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.memory.port | quote }}
            - name: MAX_MESSAGE_SIZE
              value: {{ .Values.memory.maxMessageSize | quote }}
            {{- if .Values.persistence.enabled }}
            - name: MEMORY_FILE_PATH
              value: "{{ .Values.persistence.mountPath }}/{{ .Values.persistence.memoryFileName }}"
            - name: STREAM_FILE_PATH
              value: "{{ .Values.persistence.mountPath }}/{{ .Values.persistence.streamFileName }}"
            {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "ark-cluster-memory.fullname" . }}-data
          {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}