project:
  name: dev-tests
  type: pyproject
  platform: python3
  version: 0.1.0
  framework: fastmcp
python:
  version: "3.11"
  module_name: dev_tests
devspace:
  namespace: default
  image:
    repository: dev-tests
