# DevSpace configuration for reverse-tool
version: v2beta1

# Deployment pipelines
pipelines:
  deploy: |-
    build_images --all
    create_deployments --all

  dev: |-
    create_deployments --all
    start_dev --all

# Image build configuration
images:
  reverse-tool:
    image: reverse-tool
    dockerfile: ./Dockerfile
    context: ./

# Kubernetes deployments
deployments:
  reverse-tool:
    namespace: default
    helm:
      chart:
        path: ./chart
      values:
        app:
          image:
            repository: reverse-tool
            tag: ${runtime.images.reverse-tool.tag}

# Development configuration
dev:
  reverse-tool:
    imageSelector: reverse-tool
    devImage: python:3.11-slim
    command: ["sh", "-c", "pip install uv && cd /app && uv sync && uv run python -m reverse_tool"]
    namespace: default
    logs:
      lastLines: 50
    sync:
      - path: ./:/app
        uploadExcludeFile: .dockerignore
        startContainer: true
    ssh:
      enabled: true
