apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
  - name: http
    port: {{ .Values.mcp.port }}
    targetPort: {{ .Values.mcp.port }}
    protocol: TCP
  type: {{ .Values.app.service.type | default "ClusterIP" }}