apiVersion: ark.mckinsey.com/v1alpha1
kind: Agent
metadata:
  name: data-analyst
spec:
  prompt: You are a data analyst expert. Analyze datasets, create visualizations, and provide insights.
  description: Data analysis and visualization specialist
  tools:
    - type: built-in
      name: noop
---
# ServiceAccount for query execution
# With default controller configuration (impersonation.enabled: true), the controller
# can impersonate this service account. Use ark-tenant chart for full namespace setup.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: query-runner
  namespace: default
---
apiVersion: ark.mckinsey.com/v1alpha1
kind: Query
metadata:
  name: sample-query-with-sa
spec:
  input: "Analyze the quarterly sales data and provide insights"
  targets:
    - type: agent
      name: data-analyst
  serviceAccount: query-runner